# Generated by Django 4.2.4 on 2023-11-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0016_alter_vehiclemodel_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='cab_class',
            field=models.ForeignKey(default=15,on_delete=django.db.models.deletion.CASCADE, to='cabs.cabclass'),
        ),
    ]
