# Generated by Django 4.2.4 on 2023-11-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0017_vehiclemodel_cab_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabclass',
            name='icon',
            field=models.TextField(),
        ),
    ]
