# Generated by Django 4.2.4 on 2023-12-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0018_alter_cabclass_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='cab_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabs.cabclass'),
        ),
    ]
