# Generated by Django 4.2.4 on 2023-08-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Owner_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_maker_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_plate_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'car_owner_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Car_Owner_Vehicle_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('car_owner_vehicle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance', models.CharField(blank=True, max_length=500, null=True)),
                ('RC_book', models.CharField(blank=True, max_length=500, null=True)),
                ('C_book', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'car_owner_vehicle_certificate',
            },
        ),
        migrations.CreateModel(
            name='Car_Owner_Vehicle_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('car_owner_vehicle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_front_image', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_back_image', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_left_image', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_right_image', models.CharField(blank=True, max_length=500, null=True)),
                ('driver_seat_image', models.CharField(blank=True, max_length=500, null=True)),
                ('passager_seat_image', models.CharField(blank=True, max_length=500, null=True)),
                ('front_head_light_image', models.CharField(blank=True, max_length=500, null=True)),
                ('back_head_light_image', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'car_owner_vehicle_image',
            },
        ),
    ]
