# Generated by Django 4.2.4 on 2023-09-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_owner_vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
