# Generated by Django 4.2.4 on 2023-10-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners_api', '0003_car_owner_vehicle_vehicle_type_id_car_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_booking',
            name='after_back',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='after_front',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='after_inside_car',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='after_left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='after_right',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='after_speedo_meter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='before_back',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='before_front',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='before_inside_car',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='before_left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='before_right',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='before_speedo_meter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
