# Generated by Django 4.2.4 on 2023-10-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners_api', '0005_car_booking_created_at_car_booking_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_booking',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
