# Generated by Django 4.2.4 on 2023-10-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners_api', '0006_car_booking_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.TextField(blank=True, null=True)),
                ('vehicle_video', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_owners_api.car_owner_vehicle')),
            ],
            options={
                'db_table': 'accident_support',
            },
        ),
    ]
