# Generated by Django 4.2.4 on 2023-11-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0016_alter_vehiclemodel_model_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_owners_api', '0007_accident_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_owner_vehicle',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='car_owner_vehicle',
            name='vehicle_maker_id',
        ),
        migrations.RemoveField(
            model_name='car_owner_vehicle',
            name='vehicle_model_id',
        ),
        migrations.RemoveField(
            model_name='car_owner_vehicle',
            name='vehicle_type_id',
        ),
        migrations.RemoveField(
            model_name='car_owner_vehicle_certificate',
            name='car_owner_vehicle_id',
        ),
        migrations.RemoveField(
            model_name='car_owner_vehicle_certificate',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='car_owner_vehicle_image',
            name='car_owner_vehicle_id',
        ),
        migrations.RemoveField(
            model_name='car_owner_vehicle_image',
            name='user_id',
        ),
        migrations.AddField(
            model_name='car_owner_vehicle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car_owner_vehicle',
            name='vehicle_maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabs.vehiclemaker'),
        ),
        migrations.AddField(
            model_name='car_owner_vehicle',
            name='vehicle_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabs.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='car_owner_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabs.cabtype'),
        ),
        migrations.AddField(
            model_name='car_owner_vehicle_certificate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car_owner_vehicle_certificate',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='car_owner_vehicle_image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car_owner_vehicle_image',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
