# Generated by Django 4.2.4 on 2023-11-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0016_alter_vehiclemodel_model_image'),
        ('car_owners_api', '0008_remove_car_owner_vehicle_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_owner_vehicle',
            name='vehicle_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabs.cabclass'),
        ),
    ]
