# Generated by Django 4.2.4 on 2023-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners_api', '0009_car_owner_vehicle_vehicle_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
