# Generated by Django 4.2.4 on 2023-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners_api', '0011_car_booking_applied_coupon_car_booking_basic_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=10),
        ),
    ]
