# Generated by Django 4.2.4 on 2023-12-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_owners_api', '0012_alter_car_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_owner_vehicle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
