# Generated by Django 4.2.4 on 2023-12-02 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabs', '0019_alter_vehiclemodel_cab_class'),
        ('car_owners_api', '0013_alter_car_owner_vehicle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_owner_vehicle',
            name='vehicle_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabs.cabclass'),
        ),
        migrations.AlterField(
            model_name='car_owner_vehicle',
            name='vehicle_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabs.vehiclemaker'),
        ),
        migrations.AlterField(
            model_name='car_owner_vehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabs.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='car_owner_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabs.cabtype'),
        ),
        migrations.AlterField(
            model_name='car_owner_vehicle_image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
