# Generated by Django 4.2.4 on 2023-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners_api', '0014_alter_car_owner_vehicle_vehicle_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_owner_vehicle',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
