# Generated by Django 4.2.4 on 2023-11-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabs', '0015_vehiclemodel_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabBookingPriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0.0)),
                ('platform_charge', models.IntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabs.vehiclemodel')),
            ],
            options={
                'db_table': 'cab_booking_price_setting',
            },
        ),
    ]
