# Generated by Django 4.2.4 on 2023-11-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking_admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbookingpricesetting',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='cab booking price base on per kms'),
        ),
    ]
