# Generated by Django 4.2.4 on 2023-11-29 08:23

import cab_booking_admin_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab_booking_admin_api', '0004_remove_cabbookingpricesetting_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbookingcouponcodesetting',
            name='expire_date',
            field=models.DateTimeField(default=cab_booking_admin_api.models.defualt_expire_date),
        ),
    ]
