# Generated by Django 4.2.4 on 2023-12-02 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0019_alter_vehiclemodel_cab_class'),
        ('cab_booking_admin_api', '0006_cabbookingcouponcodesetting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbookingpricesetting',
            name='cab_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cabs.cabclass'),
        ),
    ]
