# Generated by Django 4.2.4 on 2023-11-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_admin_api', '0002_city_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='CitySetting',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='LocationsSetting',
        ),
        migrations.AlterModelTable(
            name='citysetting',
            table='city_setting',
        ),
        migrations.AlterModelTable(
            name='locationssetting',
            table='locations_setting',
        ),
    ]
