# Generated by Django 4.2.4 on 2023-11-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_admin_api', '0004_vehiclerentepricesetting_extra_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerentepricesetting',
            name='extra_charge',
        ),
    ]
