# Generated by Django 4.2.4 on 2023-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_admin_api', '0006_alter_vehiclerentepricesetting_fast_kms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerentepricesetting',
            old_name='extra_charges',
            new_name='extra_kms_charge',
        ),
        migrations.AddField(
            model_name='vehiclerentepricesetting',
            name='tax_percentage',
            field=models.IntegerField(default=0, verbose_name='Tax Percentage'),
        ),
    ]
