# Generated by Django 4.2.4 on 2023-12-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_admin_api', '0009_citysetting_city_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerentepricesetting',
            name='fast_kms',
        ),
        migrations.RemoveField(
            model_name='vehiclerentepricesetting',
            name='second_kms',
        ),
        migrations.RemoveField(
            model_name='vehiclerentepricesetting',
            name='third_kms',
        ),
    ]
