# Generated by Django 4.2.4 on 2023-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='applied_coupon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
